# Use root/example as user/password credentials
version: '3.5'

services:
  db:
    image: mysql
    container_name: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      # When container is first created, this database and superuser are created
      MYSQL_DATABASE: my_project
      MYSQL_USER: project_user
      MYSQL_PASSWORD: project_password
    ports:
      - 3308:3306
    volumes:
      - ./sql:/media # Shared folder, just in case
      - ./sql:/docker-entrypoint-initdb.d # Scripts in this folder are run automatically at container creation
      # - ./sql/data:/var/lib/mysql # MySQL data folder
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db